version: '3'

services:
  # Was having troubles with Postgres connectivity dropping while DB running
  # Swapped to SQLite for the time being.
  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - 'pgdata:/var/lib/postgresql/data/'
  #   environment:
  #     POSTGRES_PASSWORD: postgres

  api:
    image: node:16
    restart: unless-stopped
    build: .devcontainer
    command: npm run dev
    volumes:
      - .:/workspace:rw
    working_dir: /workspace
    ports:
      - 8080:8080
    env_file: .env
    # depends_on:
    #   - db

volumes:
  pgdata: {}
